export const FETCH_SIMILAR_NEWS_REQUEST="FETCH_SIMILAR_NEWS_REQUEST";
export const FETCH_SIMILAR_NEWS_SUCCESS="FETCH_SIMILAR_NEWS_SUCCESS";
export const FETCH_SIMILAR_NEWS_FAILURE="FETCH_SIMILAR_NEWS_FAILURE";

export const SET_SIMILAR_NEWS="SET_SIMILAR_NEWS";